# Usar una imagen de Node.js
FROM node:18.18.2

# Establecer el directorio de trabajo en el contenedor
WORKDIR /usr/src/app

# Copiar los archivos de tu aplicación (incluyendo el package.json)
COPY package*.json ./

# Instalar las dependencias
RUN npm install

# Copiar todo el código fuente
COPY . .

RUN npm install nodemon --save-dev

# Ejecutar el script 'build' para transpilar el código (si es necesario)
RUN npm run build

# Exponer el puerto en el que se ejecutará tu servidor
EXPOSE 3000

# Comando para iniciar tu servidor en el contenedor
CMD ["npm", "run", "dev"]
