version: "3.9"

services:
  db:
    container_name: my_mysql
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: appdb
    ports:
      - "3306:3306"
    volumes:
      - "./scripts/db.sql:/docker-entrypoint-initdb.d/db.sql"